language: cpp

env:
  - CATCH_PWD=$PWD
  - PATH=$CATCH_PWD:$PATH

compiler:
  - gcc
  - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y g++-4.9 g++-5 clang-3.6
    
before_script:
    git clone https://github.com/philsquared/Catch
    
script:
   - make
   - ./test