language: cpp

sudo: false

compiler:
  - gcc

env:
  - COMPILER=g++-4.9
  - COMPILER=g++-5
  - COMPILER=clang-3.7

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    packages:
    - g++-4.9
    - g++-5
    - clang-3.7
    - valgrind
    
before_script:
    git clone https://github.com/philsquared/Catch
    
script:
   - make CXX=$COMPILER CXXFLAGS="-lstdc++"
   - ./test