language: cpp

sudo: false

compiler:
  - gcc

env:
  - COMPILER=g++-4.9
  - COMPILER=g++-5
  - COMPILER=clang-3.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - g++-5
    - clang-3.6
    
before_script:
    git clone https://github.com/philsquared/Catch
    
script:
   - make CXX=$COMPILER
   - ./test